name: My Github Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, Github Actions"
      - name: Display repo name
        run: echo "this workflow is running in ${{ github.repository}}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show current directory
        run: pwd
      - name: List files
        run: ls -la
